-- Smart Pantry schema for local/staging Supabase smoke tests.
-- Source of truth: backend_python/app/models.py
-- Keep mixed-case table and column names quoted; the FastAPI SQLModel layer expects them.

do $$
begin
  if not exists (select 1 from pg_type where typname = 'UserRole') then
    create type "UserRole" as enum ('USER', 'ADMIN');
  end if;
end $$;

create table if not exists "User" (
  "id" integer generated by default as identity primary key,
  "email" varchar not null unique,
  "fullName" varchar,
  "username" varchar unique,
  "passwordHash" varchar not null,
  "role" "UserRole" not null default 'USER',
  "encryptedProfile" varchar,
  "quotaLlmTokens" integer not null default 5000,
  "quotaRecipeCalls" integer not null default 6,
  "llmTokensUsed" integer not null default 0,
  "recipeCallsUsed" integer not null default 0,
  "maxCacheRecipeSuggestions" integer default 12,
  "maxChatMessages" integer default 4,
  "maxCacheRecipeSearchViaChat" integer default 4,
  "maxGroceriesWithExpiry" integer default 10,
  "maxGroceriesTotal" integer default 20,
  "cacheRecipeSuggestionsUsed" integer default 0,
  "chatMessagesUsed" integer default 0,
  "cacheRecipeSearchViaChatUsed" integer default 0,
  "notificationsEnabled" boolean not null default false,
  "hasPrioritySupport" boolean not null default false,
  "quotaResetAt" timestamp without time zone,
  "monthlyLimitResetAt" timestamp without time zone,
  "createdAt" timestamp without time zone not null default now(),
  "updatedAt" timestamp without time zone default now()
);

create index if not exists "ix_User_email" on "User" ("email");

create table if not exists "RefreshToken" (
  "id" integer generated by default as identity primary key,
  "tokenHash" varchar not null,
  "userId" integer not null references "User" ("id"),
  "expiresAt" timestamp without time zone not null,
  "createdAt" timestamp without time zone not null default now(),
  "revokedAt" timestamp without time zone,
  "userAgent" varchar,
  "ipAddress" varchar
);

create table if not exists "Grocery" (
  "id" integer generated by default as identity primary key,
  "userId" integer not null references "User" ("id"),
  "name" varchar not null,
  "quantity" double precision not null,
  "unit" varchar not null,
  "category" varchar not null,
  "expiryDate" timestamp without time zone,
  "addedAt" timestamp without time zone not null default now(),
  "lowStockThreshold" double precision not null default 1,
  "notes" varchar
);

create table if not exists "SavedRecipe" (
  "id" integer generated by default as identity primary key,
  "userId" integer not null references "User" ("id"),
  "recipeId" integer not null,
  "title" varchar not null,
  "image" varchar,
  "usedIngredients" jsonb,
  "missedIngredients" jsonb,
  "likes" integer not null default 0,
  "sourceUrl" varchar,
  "savedAt" timestamp without time zone not null default now(),
  "isCustom" boolean not null default false,
  "readyInMinutes" integer,
  "servings" integer,
  "instructions" text,
  "ingredientsJson" jsonb
);

create table if not exists "CookedRecipe" (
  "id" integer generated by default as identity primary key,
  "userId" integer not null references "User" ("id"),
  "recipeId" integer not null,
  "recipeTitle" varchar not null,
  "cookedAt" timestamp without time zone not null default now(),
  "rating" integer
);

create table if not exists "ShoppingList" (
  "id" integer generated by default as identity primary key,
  "userId" integer not null references "User" ("id"),
  "name" varchar not null,
  "createdAt" timestamp without time zone not null default now(),
  "updatedAt" timestamp without time zone not null default now()
);

create table if not exists "ShoppingListItem" (
  "id" integer generated by default as identity primary key,
  "shoppingListId" integer not null references "ShoppingList" ("id"),
  "name" varchar not null,
  "quantity" double precision not null,
  "unit" varchar not null,
  "checked" boolean not null default false,
  "addedAt" timestamp without time zone not null default now()
);
